{'name': 'B2B Invoice',
 'summary': "Adapt invoice for B2B",
 'version': '10.0.1.0.0',
 'author': 'Camptocamp',
 'maintainer': 'Camptocamp',
 'license': 'AGPL-3',
 'category': 'Depiltech',
 'depends': ['account'],
 'website': 'www.camptocamp.com',
 'data': ['views/company.xml',
          'views/account_invoice.xml',
          'views/report_account_invoice.xml',
          'data/ir_config_parameter.xml',
          ],
 'test': [],
 'installable': True,
 'auto_install': False,
 }
